API Validation
kanye-loves-kanye/capstone-backend-india-2023-klk pull request #5
Opened 2024-02-28 23:28 UTC by BrandonKim922

2024-02-28 23:30 UTC, elysemontano requested changes
Is this PR for validations or endpoints? I am seeing a little bit of both in here

2024-02-28 23:32 UTC, BrandonKim922 commented
> Is this PR for validations or endpoints? I am seeing a little bit of both in here

It is for both.

2024-02-28 23:47 UTC, elysemontano commented
> It is for both.

Please let me know in slack if you make a comment here. GitHub does not do a great job notifying me that there is a new comment to address.  With that, this should only be for validations based on the Trello card. Endpoints are separated into other Trello cards. Please update this PR so it only reflects validations.

2024-02-29 18:11 UTC, elysemontano approved these changes

2024-02-29 18:14 UTC, merged